### ISSUE TITLE
health patterns roadmap picture references broken URL

### ISSUE THREAD

**Issue by thisisadamo** [Alvearie/health-patterns#121]
https://github.com/Alvearie/health-patterns/blob/main/docs/roadmap.md

"Latest roadmap always here" - that link appears broken

**Comment by ewill00** [comment]
Just  to be sure we're looking at the same thing - the architecture-like picture on that  page 
     https://github.com/Alvearie/health-patterns/blob/main/docs/roadmap.md
is a png so clicking on it just goes to the png within github.  The address itself is valid, but I agree that the link from that page is misleading since it is embedded in a png.   I can rework it to take it out of the picture if it causes confusion (probably should make some other updates anyway)
