### ISSUE TITLE
Clinical Ingestion Flow fails in NIFI Clinical Ingestion process group

### ISSUE THREAD

**Issue by rguderian** [Alvearie/health-patterns#95]
NIFI Canvas at: http://beac388a-us-south.lb.appdomain.cloud:8080/nifi/

Ingesting FHIR data via NIFI API call to port 7001.   The FHIR data does not get saved to the FHIR server.   The following error is shown on the "Send to FHIR and Post Errors V2" process group:

20:35:28 UTC
ERROR
f9f77b8c-4c56-3bd6-9ab7-815c96b13a82
ingestion-nifi-0.ingestion-nifi-headless.clinical-ingestion-test.svc.cluster.local:8080

InvokeScriptedProcessor[id=f9f77b8c-4c56-3bd6-9ab7-815c96b13a82] There is no processor defined by the script

**Comment by luisgarcc** [comment]
I think this may be a known issue or at least one with a work around. Maybe it will go away when we adopt the next M&M flow. Will let @ibmatc provide more details.

**Comment by ibmatc** [comment]
This problem is caused by a known issue in Nifi. When a Nifi Groovy Script processor is loaded onto the canvas from the registry, there is a chance that it will not load properly and it will be marked broken.  This can be resolved by copying the processor, pasting it, and reconnecting the copy to replace the original (then delete the original).  This is a painful workaround, but for now it is the recommendation.  I will leave this issue open as a reminder that we need to find a better solution.

**Comment by rguderian** [comment]
Adam updated Nifi from "Mike & Mike" to resolve this issue.   Closing
